?start: exp


?exp: exp "+" exp  -> plus
     | exp "-" exp  -> minus
     | exp1

?exp1: exp1 "*" exp2 -> times
     | "-" exp1      -> neg
     | exp2

?exp2: exp2 exp3     -> app
     | exp3

?exp3: "\\" NAME "." exp -> lam
     | NAME              -> var
     | NUMBER            -> num
     | "(" exp ")"       -> parens



NAME: /[a-z_][a-zA-Z0-9_]*/         
%import common.NUMBER

%import common.WS
%ignore WS

%ignore /\/\/[^\n]*/  
%ignore /\/\*[\s\S]*?\*\//  
